# Python 3.10
name: umpire
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.7.1
  - pip:
      - absl-py
      - accelerate
      - bitsandbytes
      - evaluate
      - jsonlines
      - matplotlib
      - nltk
      - pandas
      - pillow
      - protobuf
      - rouge-score
      - scikit-learn
      - seaborn
      - sentencepiece
      - tabulate
      - transformers
      # - flash-attn # Install using `conda install -c conda-forge flash-attn`
      # - uncertainty-metrics==0.0.81 # Needs to be intalled by first downgrading to pip<24.1 first. Lastly `pip install --upgrade pip`
